### ISSUE TITLE
Linking pages improvements (meta issue)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#1026]
This meta issue is here to track possible link handling improvements

* [ ] Linking a page should be the first and most obvious way of linking in Collectives. One solution would be a new toplevel entry "Link to page" in the link section of the Text menubar. This entry could open the "Collectives pages" picker in the smart picker. #979
* [ ] The "Collectives pages" picker in the smart picker could provide a page picker (similar to the move/copy modal) additionally to just listing search results.
* [ ] When adding a link via smart picker, we should add a markdown link with the page title as title (like `[page title](/link/to/page.md?fileId=123)`) instead of just pasting the URL. #949
* [ ] When clicking a link in edit mode, it should open a popover that allows navigating to the link and/or editing the link. #845
* [ ] Link previews could show only on hover/click instead of being displayed all the time. We got quite a few complaints about link previews cluttering the page. Also related to #845

**Comment by timkrief** [comment]
Here's a suggestion: https://github.com/nextcloud/collectives/issues/1073

**Comment by timkrief** [comment]
Hi, after using collectives for quite sometime, here are two more suggestions to improve linking pages:

- #1583 
- #1584

**Comment by Thatoo** [comment]
Text-only view internal link don't translate the link to make the target page accessible when the page has been access by public shared link (not registered user), it redirect to the login page : https://github.com/nextcloud/collectives/issues/2378#issuecomment-4389250624
