### ISSUE TITLE
UX issues with internal links

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#1573]
Copied over from @estux comment at https://github.com/nextcloud/collectives/issues/1490#issuecomment-2444068563

> Hello, I confirm that internal links are completely broken! @mejo-
> I tried to make them work in every way is possible (and also encountered at least 5 different bugs and UI issues that I will list here as all are related to internal links broken).

1) About the **Popup that appears clicking on a link**
- [x] UI To improve: it doesn't make clear where people should click as it has a preview with the same text of the link on the second line. 
- [x] bug: on mobile the button in the popup to copy link text is not visible as it goes too far on the right (nextcloud/text#7272)

2) Link inside a Callout box
- [ ] bug: if a put a link with Smart Linker (both Preview or Text-only mode) in the middle of a text inside a callout box, it "breaks" the box in 2 parts, one above the link and one under the link and the link seems outside of the box, in the middle. (nextcloud/text#7271)

3) About Preview and Text-only views
- [x]  bug: the link to another Collective page, created with Smart Linker, **preview mode**, is not clickable at all from both desktop and mobile view (nextcloud/text#7384)
- [x] bug: in view mode, the link URL is displayed above above the Preview box (this feels like clutter from UI point of view)
- [x] bug: on mobile the preview box is so small that the link inside is not properly shown
- [ ] UI To improve: (In my opinion) The Preview view is too big and risks breaking the "visual balance" of the pages in Collectives, especially if links are inserted inline, in the middle of the text.
- [x] Feature/UI To improve: In Text-only view I cannot add a Placeholder for the link (like in classic Markdown syntax) as I can do with the "Insert link" button, so I always have to see long links here and there in the middle of the text.

**Comment by Thatoo** [comment]
Text-only view internal link don't translate the link to make the target page accessible when the page has been access by public shared link (not registered user), it redirect to the login page :
* https://github.com/nextcloud/collectives/issues/2378#issuecomment-4389250624

**Comment by mejo-** [comment]
Let's close this old overview issue as all listed issues have been addressed or have their own issue these days.
