### ISSUE TITLE
Improve page navigation

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#304]
The page list becomes confusing and overwhelming pretty fast if you have a lot of pages and subpages. Some obstacles we identified so far:

* The indention of subpages is not very visible and sometimes hard to spot.
* It's hard to find a particular page in a long and confusing page list.
* The default page order (by most recent change) is confusing to many people. They don't get the concept and wonder why the pages are reorders arbitrary every now and then.
* It's impossible to apply a custom page order.

This is a meta ticket to discuss improvements for page navigation.

List of subtickets to track individual improvements:

* [ ] #305 Sticky page list header
* [ ] #309 Scroll to selected page after sorting changed
* [ ] #302 Filter list pages by search string
* [ ] #300 Favourite pages
* [ ] #303 Custom page order
* [ ] #306 Fix color of badge to collapse/expand subpages
* [ ] #307 Change page order 'recently changed' to 'creation date'
