### ISSUE TITLE
Improved landing page

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#311]
The idea is to display more information about the collective on the landing page and turn it into a dashboard step by step.

* [ ] List five most recently changed pages
* [ ] List collective members avatars, sorted by most recent activity
* [ ] List of personal favourite pages (once #300 got implemented)

The editable page would be displayed below these information.

**Comment by szaimen** [comment]
As for the favorites, the same layout could be used like the one of recent pages :)

**Comment by mejo-** [comment]
Notes from discussing the mockup with @szaimen:

* Only one line (scrollable horizontally) with avatars for collective members. Tooltip shows display name, click optionally opens member modal.
* Last edited user and time in the recent pages tiles. Recent pages are scrollable horizontally as well.
* Editable page content moves blow recent pages and members and keeps full height.

**Comment by szaimen** [comment]
Hey, so I tried to incoroprate the changes (and also some that I discussed with Jan). This is my new mockup. Let me know what you think:
![image](https://github.com/nextcloud/collectives/assets/42591237/8152a774-eafe-42e4-8f9c-ea358eff0611)

Unfortunately I will be away starting form monday so if you need additional changes, probably someone else from the Design team needs to take over.

The penpot file is here: https://design.penpot.app/#/workspace/09f8f1e0-a390-11eb-bb49-81aaa3a367f9/c65f3168-697c-808c-8002-dd48bd82cca0?page-id=583600af-26f0-8056-8002-dd3a532f090e&layout=layers

**Comment by max-nextcloud** [comment]
Looks good to me. I just have some minor comments on the page list:
* The page emojis look somewhat lost with all the whitespace around. I would double their size to reduce the whitespace to the text below.
* The user bubbles should not be primary color
* It would be good to add a timestamp so one can tell wether these pages were changed yesterday or a long time ago.

**Comment by nimishavijay** [comment]
Super nice mockup and agreed with the comments! Some more minor feedback from my side:
- "Collective Members" --> "Collective members" (note the lowercase "m")
- Instead of a timestamp separately, how about changing the wording to "Edited 10 minutes ago by Alex Doe" and "Edited last week by Sam Smith", etc? :)

**Comment by jancborchardt** [comment]
> Instead of a timestamp separately, how about changing the wording to "Edited 10 minutes ago by Alex Doe" and "Edited last week by Sam Smith", etc? :)

Yep, I would even say shortening it to "**Alex Doe** 10 minutes ago" is good. Same for the description, the "Last changed by" can be cut.

And @max-nextcloud yep the mention bubbles should indeed only be primary if it is yourself, and in this case they would say "You".

**Comment by matthiastaeschner** [comment]
Dear contributors. Is there a possibility to deactivate the display of recent pages and collective members? It's a nice feature for sure, but forcing it without any visible way for deactivation is not a very good approach.

**Comment by punkyard** [comment]
Hi 
What is the way to get rid of "recent pages" and "landing page" which terribly damage the previous slick public display through public links?
For people who would need these features, would it ba possible to incorporate them in the left menu? or activate it in Settings?

Thanks a lot for your concern
